spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planeat?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
      show_sql: true

jwt:
  secret-key: ${SECRET}
  expiration: 86400000 # 1일

openapi:
  serviceKey: ${OPENAPI_KEY}